//Resources

var RESOURCES 	= 1000000;		//1.000.000
var CLASS		= 10000;		//10.000

var EXP			= RESOURCES +1;
var CASH 		= RESOURCES +2;


//GUI
var GUISTATE 		= 30000;
var PLAYER			= GUISTATE +1;
var league			= GUISTATE +2;
var TEAM			= GUISTATE +3;
var STADIUM			= GUISTATE +4;
var CLUB			= GUISTATE +5;
var PRESTIGE		= GUISTATE +6;
var POLITICS		= GUISTATE +7;
var SINGLEKICKER	= GUISTATE +8;
var FORMATION		= GUISTATE +9;
var TEAMTRAINING	= GUISTATE +10;
var MARKETING		= GUISTATE +11;
var TEAMCONTRACTS	= GUISTATE +12;
var CANCELCONTRACT	= GUISTATE +13;

//TEAM
var KEEPER			= 0;
var DEFENCE			= 1;
var MIDFIELD		= 2;
var STRIKER			= 3;
var BENCH			= 4;
var NOTNOMINATED	= 5;
var INJURED			= 6;

//Training
var TRAININGEFFECTIVITY	= 0.025;
var MATCHEFFECTIVITY	= 0.00001;
var COACHEFFICIENCY		= 0.00001;
var LEAGUEFFICIENCY		= 1;
var LEAGUEBALANCING		= 1000;
var REFERENCEAGE		= 32;
var AGEBALANCING		= 1000;
var POSITIONVSSKILL 	= 0.75;


//Timekeeping
var GAMEDAY 	= 1000; 	//1000
var FRAMERATE 	= 250; 	//120000

//New season
var GRADUATE 	= 0;
var STAY 		= 1;
var RELEGATE 	= 2;

//Stadium
var TICKETVENDOREXPONENT = 1.6;




//CLUB

var TICKETVENDORRATE = 1;


