//Resources

//Gamestate
var INIT			= 0;
var RUNNING			= 1;


//GUI
var GUISTATE 		= 30000;
var PLAYER			= GUISTATE +1;
var league			= GUISTATE +2;
var TEAM			= GUISTATE +3;
var STADIUM			= GUISTATE +4;
var CLUB			= GUISTATE +5;
var PRESTIGE		= GUISTATE +6;
var POLITICS		= GUISTATE +7;
var SINGLEKICKER	= GUISTATE +8;
var FORMATION		= GUISTATE +9;
var TEAMTRAINING	= GUISTATE +10;
var MARKETING		= GUISTATE +11;
var TEAMCONTRACTS	= GUISTATE +12;
var CANCELCONTRACT	= GUISTATE +13;
var PERSONNEL		= GUISTATE +14;
var FINANCE			= GUISTATE +15;
var STATISTICS		= GUISTATE +16;
var LEAGUEVIEW		= GUISTATE +17;
var GAMEDAYS		= GUISTATE +18;




//TEAM
var KEEPER			= 0;
var DEFENCE			= 1;
var MIDFIELD		= 2;
var STRIKER			= 3;
var BENCH			= 4;
var NOTNOMINATED	= 5;
var INJURED			= 6;

//Training
var COACHBALANCING		= 10000000;
var LEAGUEFFICIENCY		= 1;
var LEAGUEBALANCING		= 100000;
var REFERENCEAGE		= 30;
var AGEBALANCING		= 200000;
var TALENTBALANCING		= 10000;
var POSITIONVSSKILL 	= 0.75;

//Salary and Value
var SALARYCONSTANT = 2;
var VALUECONSTANT = 1000;
var VALUEAGEDEDUCTION = 1.25;

var COACHSALARYCONSTANT = 2;
var COACHSALARYEXPONENT = 2;

//Timekeeping
var GAMEDAY 	= 250;//1000;
var FRAMERATE 	= 250;

//New season
var GRADUATE 	= 0;
var STAY 		= 1;
var RELEGATE 	= 2;

//Stadium
var TICKETVENDOREXPONENT = 1.7;
var EXPANDTERRACEPRICE = 25;
var EXPANDTERRACECOMFORT = 1.25;

//MARKETING
var PERIMETERADVERTISINGEFFICIENCY = 0.0005;
var PERIMETERADVERTISINGREVENUEBASE = 2;
var PERIMETERADVERTISINGREVENUEMULTIPLIER = 20;
var PERIMETERADVERTISINGMONTHLYCOST = 2;
var PERIMETERADVERTISINGRECOSTMULTIPLIER = 20;
var PERIMETERADVERTISINGMONTHLYINCREMENT = 0.5;
var PERIMETERADVERTISINGBASECOST = 75;
var PERIMETERADVERTISINGCOSTINCREMENT = 0.1;

//CLUB

var TICKETVENDORRATE = 1;


